---
##########################
## Hadolint config file ##
##########################
ignored:
  - DL3003 # Use WORKDIR to switch to a directory.
  - DL3033 # require yum specific versions
  - DL4001
  - DL3013
