name: Build manylinux aarch64 + cuda image

on:
  push:
    branches:
      - main
    paths:
      - 'manylinux_cuda_aarch64/*'
      - '.github/workflows/build-manylinux-cuda-aarch64.yml'
  pull_request:
    paths:
      - 'manylinux_cuda_aarch64/*'
      - '.github/workflows/build-manylinux-cuda-aarch64.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 5'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      runs-on: 'ubuntu-24.04-arm'
      docker-platforms: linux/arm64
      docker-context: ./manylinux_cuda_aarch64
      dockerfile: ./manylinux_cuda_aarch64/Dockerfile
      image_subpath: manylinux_cuda_aarch64
      alternate-latest-mode: true
      push: ${{ github.event_name != 'pull_request' }}
