name: Build IPS Image

on:
  push:
    branches:
      - main
    paths:
      - 'ips/*'
      - '.github/workflows/build-ips.yml'
  pull_request:
    paths:
      - 'ips/*'
      - '.github/workflows/build-ips.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 5'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      alternate-latest-mode: true
      docker-context: "./ips"
      dockerfile: "./ips/Dockerfile"
      image_subpath: "ips"
